// <auto-generated />
using ApplicationCore.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApplicationCore.Migrations.RealTime
{
    [DbContext(typeof(RealTimeContext))]
    [Migration("20190116055010_edit data model")]
    partial class editdatamodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplicationCore.Models.Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Date");

                    b.Property<string>("Indicator");

                    b.Property<int>("QuoteId");

                    b.Property<int>("Signal");

                    b.Property<string>("Text");

                    b.Property<int>("Time");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("Data");
                });

            modelBuilder.Entity("ApplicationCore.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Date");

                    b.Property<int>("High");

                    b.Property<int>("Low");

                    b.Property<int>("Open");

                    b.Property<int>("Price");

                    b.Property<int>("Time");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("ApplicationCore.Models.Data", b =>
                {
                    b.HasOne("ApplicationCore.Models.Quote", "Quote")
                        .WithMany("DataList")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
